#spring:
#  datasource:
#    url: "jdbc:mysql://127.0.0.1:3306/newspiral8?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
#     username: "root"
#     password: "xuxm"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: "ledger-mgr-application"
#mybatis:
#  mapper-locations: classpath*:com/jinninghui/newspiral/ledger/mgr/impl/mysql/*.xml